[project]
name = "odoo-addons-oca-route-planning"
version = "18.0.20260701.0"
dependencies = [
    "odoo-addon-route_planning==18.0.*",
    "odoo-addon-route_planning_sale_stock==18.0.*",
    "odoo-addon-route_planning_stock==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
